dim_ranges:
    count:
        type: discrete
        possibilities: 4
    perc:
        type: continuous
        range: [0,1]
    ratio:
        type: multiplicative
        range: [0.0001,1.0]
aprox_reward_stdev: 0.5
num_fidelities: 2
